version: "3"

services:
  app:
    build:
      context: './app'
    environment:
      - DBHOST=db
    ports:
      - 3000:3000
    restart: on-failure
  db:
    image: mongo:3.6
    ports:
      - 27017:27017