version: "3"

services:
  proxy:
    image: karibu/haproxy
    environment:
      - HAP_FRONTEND_PORT=3000
      - HAP_BACKEND_IP=app
      - HAP_BACKEND_PORT=3000
    ports:
      - 3000:3000
  app:
    build:
      context: './app'
    environment:
      - DBHOST=db
    restart: on-failure
  db:
    image: mongo:3.6
    ports:
      - 27017:27017